codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85...95" # coverage lower than 85 is red, higher than 95 green, between color code no change.
  status:
    project:
      default:
        target: auto
        threshold: 5.0 # allow for 5% reduction of coverage without failing

    # do not run coverage on patch nor changes. Check overall quality.
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

ignore:
  # ignore the third_party directory
  - "third_party"
